###
GET http://localhost:3100/api/things


###
POST http://localhost:3100/api/things


###
GET http://localhost:3100/api/agents/1


###
GET http://localhost:3100/api/properties?agentEmail=nickexample003@gmail.com&page=2


###
GET http://localhost:3100/api/properties?agentEmail=olga@example.com&minPrice=200000

###
GET http://localhost:3100/api/properties/A003N


###
POST http://localhost:3100/api/agents/1/send-mail
content-type: application/json

{
  "info": {
    "name": "dfghjk",
    "email": "g@example.com",
    "message": "dfghjkl;",
    "propertyId": "B1902"
  }
}


###
GET http://localhost:3100/api/properties/agent

###
GET http://localhost:3100/api/properties?manager=alex.roy.manager@gmail.com

###

GET http://localhost:3100/api/agents