import React, { Component } from "react";
import { Link, withRouter } from "react-router-dom";
import Header from "../components/header/header";
import PropertyList from "../components/propertyList/propertyList";
import Footer from "../components/footer/footer";

export const flats = [
  { id: "1", city: "Kuiv", rooms: "3" },
  { id: "2", city: "Odessa", rooms: "2" },
  { id: "3", city: "Lviv", rooms: "1" },
];

class Index extends Component {
  constructor(props) {
    super(props);
    this.props = props;
  };

  render() {
    // console.log()
    return (
      <>
        <Header title="Properties" />
        <PropertyList
          defaultView="grid"
          properties={[
            {
              mode: "grid",
              picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
              link: "some link",
              deal: "sale",
              type: "townhouse",
              price: 123000,
              title: "Dream Apartment for Young Family",
              location: ['Pasadena', 'California'],
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
              details: { area: 1320, bedrooms: 2, bathrooms: 2 },
              },   
            {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 284300,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InhyNHlxdG4wem1yZy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.JGd6Ymap_AOhFskJzYWTkUsPG_SuuewmEcUEDn4QJrs/image;s=1280x1024;q=80",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2859990,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 770000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 767000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRlaDFxY25kd2NnbDItRUNPU1lTVEVNIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.M38sUM2uYlF1aR2NZlqz6TDZ-p-xj75LdVy7cOzn_rs/image;s=1280x1024;q=80",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Strefa Cegielniakonu. Dodatkowo balkony na ostatnich piętrach będą posiadać zadaszenie w formie ażurowej. Obiekty zostaną wyposażone w duże przeszklenia – dzięki czemu mieszkania będą odpowiednio doświetlone – oraz zielone dachy. Do dyspozycji mieszkańców będą również miejsca do relaksu",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 141410,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 9990000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 4440000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InM0MDUza3V2YjkyejItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.I16gd70fuJbqZR6mNW2wXdzEflLIRUIaUlBSk1tfIfM/image;s=1280x1024;q=80.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 5000, bedrooms: 5, bathrooms: 4 },
            }, {
            mode: "grid",
            picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InJvZGRlMGlhaHJwODItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.QT_ZqcB8G6g7ffZdmMxcFTs0eSdjXr5T-kocxmsP_bk/image;s=1280x1024;q=80",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 10000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 5320400,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 1320, bedrooms: 2, bathrooms: 2 },
            }, {
            mode: "grid",
            picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
            link: "some link",
            deal: "sale",
            type: "townhouse",
            price: 2850000,
            title: "Dream Apartment for Young Family",
            location: ['Pasadena', 'California'],
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
            details: { area: 5000, bedrooms: 5, bathrooms: 4 },
            },]} 
        />
        <Footer />


        <Link to="/component_gallery">component gallery</Link>
       <ul>
         {flats.map((item) => {
            return (
              <li key={item.id}>
                <Link to={`/${item.id}`}>{item.city}</Link>
              </li>
            );
          })}
        </ul>
      </>
    );
  }
}

export default withRouter(Index);
