import React, { Component } from "react";
import { Link, withRouter } from "react-router-dom";
import Header from "../components/header/header";
import PropertyList from "../components/propertyList/propertyList";
import Footer from "../components/footer/footer";

export const properties = [
  {
    id: "1",
    mode: "grid",
    picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
    link: "some link",
    deal: "sale",
    type: "townhouse",
    price: 123000,
    title: "Dream Apartment for Young Family",
    location: ['Pasadena', 'California'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
    details: { area: 1320, bedrooms: 2, bathrooms: 2 },
    },   
  {
    id: "2",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 284300,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "3",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "4",
  mode: "grid",
  picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InhyNHlxdG4wem1yZy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.JGd6Ymap_AOhFskJzYWTkUsPG_SuuewmEcUEDn4QJrs/image;s=1280x1024;q=80",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2859990,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "5",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "6",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "7",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "8",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 770000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "9",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "10",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "11",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 767000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "12",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "13",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "14",
  mode: "grid",
  picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRlaDFxY25kd2NnbDItRUNPU1lTVEVNIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.M38sUM2uYlF1aR2NZlqz6TDZ-p-xj75LdVy7cOzn_rs/image;s=1280x1024;q=80",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Strefa Cegielniakonu. Dodatkowo balkony na ostatnich piętrach będą posiadać zadaszenie w formie ażurowej. Obiekty zostaną wyposażone w duże przeszklenia – dzięki czemu mieszkania będą odpowiednio doświetlone – oraz zielone dachy. Do dyspozycji mieszkańców będą również miejsca do relaksu",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "15",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 141410,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "16",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "17",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 9990000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "18",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 4440000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "19",
  mode: "grid",
  picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InM0MDUza3V2YjkyejItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.I16gd70fuJbqZR6mNW2wXdzEflLIRUIaUlBSk1tfIfM/image;s=1280x1024;q=80.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "20",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "21",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "22",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "23",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "24",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 5000, bedrooms: 5, bathrooms: 4 },
  }, {
    id: "25",
  mode: "grid",
  picture: "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InJvZGRlMGlhaHJwODItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.QT_ZqcB8G6g7ffZdmMxcFTs0eSdjXr5T-kocxmsP_bk/image;s=1280x1024;q=80",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "26",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 10000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "27",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "28",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "29",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 5320400,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "30",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 1320, bedrooms: 2, bathrooms: 2 },
  }, {
    id: "31",
  mode: "grid",
  picture: "https://storage01.tea.ru/medialibrary/2d0/2d0f6ed220d03e626e10a9d5712a4c89/92cce96f3a2c1e7e00e5f3e00f31a65f.jpg",
  link: "some link",
  deal: "sale",
  type: "townhouse",
  price: 2850000,
  title: "Dream Apartment for Young Family",
  location: ['Pasadena', 'California'],
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed arcu lectus. Praesent eget turpis vehicula, tempor libero sodales, lobortis erat. Etiam nulla odio, imperdiet sed tellus at, rhoncus commodo diam…",
  details: { area: 5000, bedrooms: 5, bathrooms: 4 },
  },]

class Index extends Component {

  render() {
    return (
      <>
        <Header title="PROPERTIES" />
        <PropertyList
          defaultView="grid"
          properties={properties} 
        />
        <Footer />
      </>
    );
  }
}

export default withRouter(Index);
